export const POST_STATUS = {
  APPROVED: "APPROVED",
  CREATED_PENDING: "CREATE_PENDING",
  CREATED_REJECT: "CREATE_REJECT",
  UPDATE_PENDING: "UPDATE_PENDING",
  UPDATE_REJECTED: "UPDATE_REJECTED",
  HIDDEN: "HIDDEN",
};
