export const POST_STATUS = {
  APPROVED: "APPROVED",
  CREATED_PENDING: "CREATED_PENDING",
  CREATED_REJECT: "CREATED_REJECT",
  UPDATE_PENDING: "UPDATE_PENDING",
  UPDATE_REJECTED: "UPDATE_REJECTED",
  HIDDEN: "HIDDEN",
};
